version: '2'
services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /var/www/public
    command: 'php -S 0.0.0.0:8888'
    ports:
        - "8888:8888"
    volumes:
      - ./../backend/:/var/www
    container_name: abicart_back

  frontend:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
      - ./../frontend/:/usr/share/nginx/html
    container_name: abicart_front


